### PR TITLE
Fixed: Ray-sphere intersection

### LINKED ISSUE #121: `ray<Thing>Intersection()` returns bool if ray didn't hit <thing>, leading to errors
**Describe the bug**
ray\<Thing\>Intersection() return their hitpos between the defined ray and the target. 
However, if the defined ray misses the target, they return a bool.

**To Reproduce**
1. Call ray\<Thing\>Intersection in a configuration above where the ray misses the target.
`A = raySphereIntersection(vec(0,0,0),vec(-1,0,0),vec(2,0,0),1)`
2. Use the return value as any argument.
`print(A)`
4. E2 subsequently errors when ran.

**Expected behavior**
In the context of E2, the most reasonable behavior in this case would be for the functions to return a zero , inf, or nan vector.

### PR DESCRIPTION
**Pull request by dvdvideo1234**
Fixes #121

### CODE REVIEW

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua [hunk 1]
```diff
@@ -216,47 +216,14 @@ local function RayCircleIntersection( Start, Dir, Pos, Normal, Radius )
...
-
-			return HitPos
-		end
-
-	end
-	--]]
-
-	return false
-
+  local A = Dir:LengthSqr(); if(A < 0) then return nil end
```
Comment (thegrb93) [inline lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua:219]: A can't be < 0 so this if check isn't doing anything

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua [hunk 2]
```diff
@@ -216,47 +216,14 @@ local function RayCircleIntersection( Start, Dir, Pos, Normal, Radius )
...
+  local R = Vector(Start) R:Sub(Pos) -- Margin less than distance
+  local B, C = 2 * Dir:Dot(R), (R:LengthSqr() - Radius^2)
```
Comment (thegrb93) [inline lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua:221]: Please don't have multiple equations on one line.

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua [hunk 3]
```diff
@@ -216,47 +216,14 @@ local function RayCircleIntersection( Start, Dir, Pos, Normal, Radius )
...
+  local D = (B^2 - 4*A*C); if(D < 0) then return nil end -- Img roots
+  local K = 1 / (2*A); D, B = K*math.sqrt(D), -B*K
+  local P = Vector(Dir); P:Mul(B + D); P:Add(Start)
+  local M = Vector(Dir); M:Mul(B - D); M:Add(Start)
+  return P, M -- Return the intersected +/- root point
```
Comment (thegrb93) [inline lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua:226]: We're returning two values, but the E2 is only using one

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua [hunk 4]
```diff
@@ -1349,7 +1316,8 @@ e2function vector rayCircleIntersection( vector start, vector dir, vector pos, v
 end
 
 e2function vector raySphereIntersection( vector start, vector dir, vector pos, number radius )
-	return RaySphereIntersection( start, dir, pos, radius )
+	local P = RaySphereIntersection( start, dir, pos, radius )
+  return (P ~= nil) and P or Vector()
```
Comment (thegrb93) [inline lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua:1320]: Just `P or Vector()` should work. Or just make RaySphereIntersection return Vector() instead of nil.

**Review by thegrb93 — CHANGES_REQUESTED** [review]

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua (hunk 4 above)
Comment (dvdvideo1234) [reply lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua]: Fixed in https://github.com/wiremod/wire-extras/pull/122/commits/eaf547b2b4d89be675565047956acdc118204027

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua (hunk 3 above)
Comment (dvdvideo1234) [reply lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua]: Fixed in https://github.com/wiremod/wire-extras/pull/122/commits/eaf547b2b4d89be675565047956acdc118204027

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua (hunk 2 above)
Comment (dvdvideo1234) [reply lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua]: Fixed in https://github.com/wiremod/wire-extras/pull/122/commits/eaf547b2b4d89be675565047956acdc118204027

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua (hunk 1 above)
Comment (dvdvideo1234) [reply lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua]: Fixed in https://github.com/wiremod/wire-extras/pull/122/commits/eaf547b2b4d89be675565047956acdc118204027

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua [hunk 5]
```diff
@@ -216,47 +216,21 @@ local function RayCircleIntersection( Start, Dir, Pos, Normal, Radius )
...
+	local C = (R:LengthSqr() - Radius^2)
+	local D = (B^2 - 4*A*C)
+	if(D < 0) then return nil end -- Img roots
+	local K = 1 / (2*A)
+	
+	D, B = K*math.sqrt(D), -B*K
+	
+	local P = Vector(Dir)
+				P:Mul(B + D)
+				P:Add(Start)
```
Comment (thegrb93) [inline lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua:232]: These can be the same line. It's the equations I didn't like being one line.

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua [hunk 6]
```diff
@@ -216,47 +216,21 @@ local function RayCircleIntersection( Start, Dir, Pos, Normal, Radius )
...
-		end
-
-	end
-	--]]
-
-	return false
-
+	local A = Dir:LengthSqr()
+	local R = Vector(Start)
+				R:Sub(Pos)
```
Comment (thegrb93) [inline lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua:221]: This can just be `local R = Start - Pos`

**Review by thegrb93 — CHANGES_REQUESTED** [review]

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua [hunk 7]
```diff
@@ -216,47 +216,21 @@ local function RayCircleIntersection( Start, Dir, Pos, Normal, Radius )
...
-
-			return HitPos
-		end
-
-	end
-	--]]
-
-	return false
-
+	local A = Dir:LengthSqr()
```
Comment (thegrb93) [inline lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua:219]: Need to check if A is 0 actually since line 226 will divide by 0 otherwise.

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua [hunk 8]
```diff
@@ -216,47 +216,21 @@ local function RayCircleIntersection( Start, Dir, Pos, Normal, Radius )
...
+	local B = 2 * Dir:Dot(R)
+	local C = (R:LengthSqr() - Radius^2)
+	local D = (B^2 - 4*A*C)
+	if(D < 0) then return nil end -- Img roots
+	local K = 1 / (2*A)
+	
+	D, B = K*math.sqrt(D), -B*K
+	
+	local P = Vector(Dir)
+				P:Mul(B + D)
```
Comment (thegrb93) [inline lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua:231]: Change `P:Mul(B + D)` to `P:Mul(S)` And change lines 226-228 to `local S = (math.sqrt(D) - B) / (2*A)`

Comment (dvdvideo1234) [reply lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua]: Fixed in: https://github.com/wiremod/wire-extras/pull/122/commits/775c7897a3bf7b0edc4807287c961ee7563bd4b7

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua (hunk 7 above)
Comment (dvdvideo1234) [reply lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua:219]: Fixed in: https://github.com/wiremod/wire-extras/pull/122/commits/775c7897a3bf7b0edc4807287c961ee7563bd4b7

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua (hunk 6 above)
Comment (dvdvideo1234) [reply lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua]: Fixed in: https://github.com/wiremod/wire-extras/pull/122/commits/775c7897a3bf7b0edc4807287c961ee7563bd4b7

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua (hunk 5 above)
Comment (dvdvideo1234) [reply lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua]: Fixed in: https://github.com/wiremod/wire-extras/pull/122/commits/775c7897a3bf7b0edc4807287c961ee7563bd4b7

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua [hunk 9]
```diff
@@ -1349,7 +1318,7 @@ e2function vector rayCircleIntersection( vector start, vector dir, vector pos, v
 end
 
 e2function vector raySphereIntersection( vector start, vector dir, vector pos, number radius )
-	return RaySphereIntersection( start, dir, pos, radius )
+	return (RaySphereIntersection( start, dir, pos, radius ) or Vector()
```
Comment (Vurv78) [inline lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua:1321]: Syntax error?

**Review by Vurv78 — DISMISSED** [review]
Also in the future add "Fixes #PR" to your PRs so it auto-closes and you don't need to ping for us to close an issue. I've edited it for you

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua [hunk 10]
```diff
@@ -217,19 +217,14 @@ end
 
 local function RaySphereIntersection( Start, Dir, Pos, Radius )
 	local A = Dir:LengthSqr()
-	local R = Vector(Start)
-				R:Sub(Pos)
+  if(A == 0) then return nil end -- Div zero
```
Comment (thegrb93) [inline lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua:220]: Need tab

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua (hunk 9 above)
Comment (thegrb93) [reply lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua:1321]: At this point, just make RaySphereIntersection return Vector() instead of nil.

**Comment by dvdvideo1234** [comment]
> Also in the future add "Fixes #PR" to your PRs so it auto-closes and you don't need to ping for us to close an issue. I've edited it for you

Yeah... I've added this `Fixes Issue #..` But is dos not link them or display any activity if that ever happens. I must not have rights or something...

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua (hunk 10 above)
Comment (dvdvideo1234) [reply lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua]: Fixed in: https://github.com/wiremod/wire-extras/pull/122/commits/2357f0fa69a3b98433934285d50a878025fe9223

File: lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua (hunk 9 above)
Comment (dvdvideo1234) [reply lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua]: Fixed in: https://github.com/wiremod/wire-extras/pull/122/commits/2357f0fa69a3b98433934285d50a878025fe9223

**Comment by Vurv78** [comment]
> > Also in the future add "Fixes #PR" to your PRs so it auto-closes and you don't need to ping for us to close an issue. I've edited it for you
> 
> 
> 
> Yeah... I've added this `Fixes Issue #..` But is dos not link them or display any activity if that ever happens. I must not have rights or something...

Permissions don't matter, it just needs to be a specific string that github scans for. Most common is Fixes #PR but theres also Closes #PR and some others afaik

**Review by thegrb93 — APPROVED** [review]

**Comment by dvdvideo1234** [comment]
My only concern for it returning two roots and picking the additive one is that it rather must return the root having positive dot product and is closer to the sphere.
When origin is outside of the sphere:
image
When origin is inside the circle:
image
In my 2D complex numbers engine I use this check to swap return values:
```lua
  if(cO:isInCircle(cC, nR)) then return xP, xM end
  return xM, xP -- Outside the circle
```

**Comment by dvdvideo1234** [comment]
Do you agree with this resolution to return the correct circle side @thegrb93  ?

**Comment by thegrb93** [comment]
I don't know. Feel free to open a new PR though if more changes are needed.
